version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled"
s3_bucket = "sam-bootstrap-bucket-3bf4c4f6-69dd-4373-b722-1f22526fa162"
s3_prefix = "serverless-saas-tenant"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"
